# Generated by Django 5.1 on 2025-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('simple', 'Simple answer'), ('multiple', 'Multiple answer')], default='simple', max_length=64, verbose_name='Question type'),
        ),
    ]
