# Generated by Django 5.1 on 2025-03-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservideo',
            options={'ordering': ('video__order',), 'verbose_name': 'User video', 'verbose_name_plural': 'User videos'},
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score (%)'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score (%)'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score (%)'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score (%)'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='core.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='usertext',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_texts', to='core.text', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.userlesson', verbose_name='User lesson'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.video', verbose_name='Video'),
        ),
    ]
