# Generated by Django 5.2.3 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_about_en_lesson_about_kk_lesson_about_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last user update'),
        ),
    ]
