# Generated by Django 5.1 on 2025-03-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usertest_options_usertext_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test', to='core.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test', to='core.userlesson', verbose_name='User lesson'),
        ),
        migrations.AlterField(
            model_name='usertext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_text', to='core.text', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='usertext',
            name='user_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_text', to='core.userlesson', verbose_name='User lesson'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='core.userlesson', verbose_name='User lesson'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='core.video', verbose_name='Video'),
        ),
    ]
