# Generated by Django 5.1 on 2025-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_name_en_category_name_kk_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
    ]
