# Generated by Django 5.2.3 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_last_profile_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_account_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last account update'),
        ),
    ]
