# Generated by Django 5.1 on 2025-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertest_test_alter_usertest_user_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('no-started', 'No started'), ('in-progress', 'In progress'), ('finished', 'Finished')], default='no-started', max_length=64, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='status',
            field=models.CharField(choices=[('no-started', 'No started'), ('in-progress', 'In progress'), ('finished', 'Finished')], default='no-started', max_length=64, verbose_name='Status'),
        ),
    ]
