# Generated by Django 5.1 on 2025-02-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscription_userpayment_usersubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpayment',
            options={'verbose_name': 'User payment', 'verbose_name_plural': 'User payments'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'User subscription', 'verbose_name_plural': 'User subscriptions'},
        ),
    ]
