# Generated by Django 5.2.1 on 2025-05-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq_alter_blog_options_blog_shortcut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='shortcut',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Shortcut'),
        ),
    ]
