# Generated by Django 5.2.1 on 2025-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blog_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Key'),
        ),
    ]
