# Generated by Django 5.1 on 2025-03-31 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_test_content',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.usertest', verbose_name='Test'),
        ),
    ]
