# Generated by Django 5.2.1 on 2025-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_slug_alter_category_slug_alter_language_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Key'),
        ),
    ]
