# Generated by Django 5.1 on 2025-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Is unlimited'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration days'),
        ),
    ]
