# Generated by Django 5.1 on 2025-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscription_is_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
