# Generated by Django 5.1 on 2025-03-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscription_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('order',), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
