# Generated by Django 5.1 on 2025-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usercourse_userchapter_userlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Google avatar'),
        ),
    ]
