# Generated by Django 5.1 on 2025-03-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_google_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapter',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='current_lesson',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
